meshmode/array_context.py, requirements.txt, test/test_meshmode.py
The purpose of this PR is to add some if_positive capability to the array-context numpy workalike.
=> Add test and implementation for three-argument-where

doc/conf.py, meshmode/discretization/poly_element.py, requirements.txt, setup.py, test/test_meshmode.py
cc @rckirby @xywei @tisaac @benSepanski
=> Add support for Toby Isaac's recursive nodes

meshmode/discretization/__init__.py, meshmode/discretization/poly_element.py
@MTCam Could you provide a review?
=> Allow getting mode IDs from the element group

meshmode/dof_array.py, test/test_meshmode.py
=> DOFArray: add, test elwise comparison operators

meshmode/array_context.py, requirements.txt, test/test_chained.py, test/test_meshmode.py, test/test_partition.py, test/test_refinement.py
=> Add pytest fixture for PyOpenCLArrayContext

meshmode/array_context.py
=> PyOpenCLArrayContext: warn about lack of allocator only on GPUs

meshmode/discretization/visualization.py
=> Let write_parallel_vtk_file work with a None communicator

meshmode/mesh/generation.py, test/test_meshmode.py
=> Allow generation of X-structured meshes

.github/workflows/ci.yml, .gitlab-ci.yml, .test-conda-env-py3.yml, doc/interop.rst, meshmode/discretization/poly_element.py, meshmode/interop/nodal_dg.py, test/test_interop.py
=> Nodal-DG interop

meshmode/array_context.py
This should make it possible to merge https://github.com/inducer/grudge/pull/23 unchanged.
cc @nchristensen fischer1 matthiasdiener
=> Add wait_event_queue_legnth feature to PyOpenCLArrayContext

meshmode/array_context.py
=> Drastically limit wait_for_event_queue_length for pytest runs

meshmode/mesh/io.py, test/test_meshmode.py
This seems to fix #62 locally.
=> Use correct node count in gmsh reader

meshmode/mesh/generation.py, requirements.txt, setup.py, test/test_meshmode.py
=> Rename group_factory to group_cls in mesh generation

meshmode/discretization/poly_element.py, meshmode/discretization/visualization.py, requirements.txt, test/test_meshmode.py
Depends on inducer/pyvisfile#11.
=> Add visualization for quad VTK_LAGRANGE elements

meshmode/array_context.py
=> Undo limiting of wait_event_queue_length for CI

meshmode/mesh/tools.py, setup.py, test/test_meshmode.py
As implicitly promised in inducer/modepy#13.
=> Use nd_quad_submesh replacement from modepy

meshmode/mesh/generation.py, test/test_mesh.py
=> Gen rect mesh non equal args

.github/workflows/ci.yml, .test-conda-env-py3.yml, meshmode/discretization/connection/projection.py
=> Github Conda CI: Run with mpi4py

meshmode/array_context.py, meshmode/dof_array.py, test/test_array.py
=> Recurse on obj arrays

meshmode/array_context.py
cc https://github.com/illinois-ceesd/mirgecom/pull/159#discussion_r530575775
=> add pytest_generate_tests_for_pyopencl_array_context to doc

meshmode/interop/firedrake/mesh.py
https://github.com/firedrakeproject/firedrake/commit/1e835859e9150b5e38a24f41ce44456e538ab253
=> Track Firedrake's renaming _topology_dm to topology_dm

meshmode/dof_array.py
Context: https://github.com/illinois-ceesd/mirgecom/pull/188/
=> Make DOFArrays picklable via global-state context manager

meshmode/array_context.py
=> Move options checking into (memoized) transform_loopy_program, to save repeated checks

meshmode/discretization/visualization.py
Currently, the visualizer code checks whether dataclass attributes are `None` or not, but it doesn't check for empty object arrays. This is needed by illinois-ceesd/mirgecom#196 for graceful handling of optional scalars. (Without the check, the "no scalars" case runs into an error inside `separate_by_real_and_imag` when it tries to determine the data type of `field[0]`.)
=> Make visualizer work with zero-length object arrays

meshmode/discretization/connection/chained.py, meshmode/discretization/connection/opposite_face.py, meshmode/discretization/connection/projection.py, meshmode/dof_array.py, meshmode/interop/firedrake/connection.py, meshmode/mesh/__init__.py, meshmode/mesh/generation.py, meshmode/mesh/io.py, meshmode/mesh/processing.py, meshmode/mesh/refinement/__init__.py, meshmode/mesh/refinement/no_adjacency.py, meshmode/mesh/refinement/utils.py, test/test_chained.py, test/test_meshmode.py
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> Fix a bunch of numpy 1.20 deprecation warnings

meshmode/mesh/processing.py
Helps fix illinois-ceesd/mirgecom#202.
=> Speed up _compute_global_elem_to_part_elem

.github/workflows/ci.yml, .test-conda-env-py3.yml
Fixes #113
Draft until:
Inspired by https://github.com/inducer/loopy/pull/220
=> Add CI jobs for downstream CI

.ci/install-for-firedrake.sh
=> Do not (try to) install pytential for Firedrake tests

examples/moving-geometry.py, meshmode/discretization/poly_element.py
Adds a simple example with a moving mesh to track some progress in #123.
=> Add moving mesh example

meshmode/dof_array.py
For context: https://github.com/illinois-ceesd/mirgecom/issues/302
=> Drop dependency on decorator module

meshmode/dof_array.py
=> Fix obj_or_dof_array_vectorized_n_args for class methods

meshmode/mesh/processing.py
Does exactly what the title says!
=> Remove deprecated function mp.simplex_best_available_basis

.github/workflows/ci.yml
=> enable mirgecom CI

meshmode/discretization/poly_element.py
=> In 1D QuadratureSimplexElementGroup, set force_dim_axis to True

meshmode/discretization/poly_element.py
@alexfikl Could you take a look?
cc @thomasgibson
=> Fix 0d quadrature rules 

meshmode/distributed.py
Fixes #162.
I wasn't loving the idea of doing the pickling ourselves, so I tried to come up with an alternate fix. This one seems to work. @matthiasdiener Am I doing anything crazy here, or does this look ok?
=> Fix irecv issue in MPIBoundaryCommSetupHelper

examples/simple-dg.py, meshmode/discretization/connection/__init__.py, meshmode/discretization/connection/chained.py, meshmode/discretization/connection/direct.py, meshmode/discretization/connection/same_mesh.py, meshmode/discretization/visualization.py
Towards https://github.com/inducer/grudge/issues/65.
cc @nchristensen
@alexfikl, what do you think? (I'd request a review, but somehow I can't?)
=> Avoid creating a separate visualization discretization when avoidable

meshmode/array_context.py
=> Add comment explaining why einsum lives in actx, not actx.np

.ci/install-downstream.sh, .github/workflows/ci.yml
Background: #148 likely causes mirgecom CI failures in parallel execution
=> CI: test mirgecom examples

meshmode/array_context.py
=> Explain the role of actx.np.equal et al

meshmode/mesh/processing.py, test/test_mesh.py
* Made `affine_map` also take numbers, to scale uniformly in all directions.
* Added a `rotate_mesh_around_axis`, which just constructs the rotation matrix and calls `affine_map`.
=> Add wrapper around affine_map for rotation

meshmode/discretization/connection/direct.py
=> Add apologetic note to InterpolationBatch.to_element_face

meshmode/dof_array.py, test/test_array.py
=> Add unflatten_like

.github/workflows/ci.yml, .gitlab-ci.yml
=> Drop extra CIs for loopy kernel callables

test/test_array.py
I managed to reproduce this locally and it seems to just be an issue in the test.
Fixes #214.
=> Fix nan in unflatten test

examples/simple-dg.py, meshmode/discretization/__init__.py, meshmode/dof_array.py, requirements.txt, test/test_interop.py
=> Improve freeze/thaw usability

meshmode/array_context.py
Well, that was anticlimactic. :facepalm: 
Closes https://github.com/illinois-ceesd/mirgecom/issues/406
=> PyOpenCLArrayContext.transform_loopy_program: actually return transformed program

meshmode/discretization/connection/direct.py
Context: illinois-ceesd/mirgecom#468
Works around https://github.com/pocl/pocl/issues/979
=> Add workaround for `compose_index_maps` kernel issue

meshmode/mesh/__init__.py
=> Fix is_affine_simplex_group for empty element groups

examples/moving-geometry.py, examples/plot-connectivity.py, experiments/refinement-playground.py, meshmode/mesh/generation.py, meshmode/mesh/visualization.py, test/test_mesh.py, test/test_meshmode.py, test/test_refinement.py, test/test_visualization.py
As suggested, it just does the same thing as the simplex-based icosahedron generator.
=> Add a cubed sphere

meshmode/mesh/__init__.py
Not sure why it wasn't one before, but it looks like it can be now.
=> Make `_FaceIDs` a dataclass

meshmode/mesh/generation.py
This reworks the torus construction to have smoother looking element boundaries (the commit message has a longer explanation).
As far as I can tell, both were "high-order" (we have some tests in pytential that check the curvature), but this is cleaner.
TODO
=> Improve torus parametrization

.gitlab-ci.yml, examples/parallel-vtkhdf.py, meshmode/discretization/visualization.py, test/test_visualization.py
Found another issue when trying to use the high-order Lagrange elements. Apparently the offsets need to start at 0.
=> Fix VTKHDF visualization on Lagrange elements

meshmode/mesh/visualization.py
Was looking to see how that's done and noticed a typo.
=> Use input file name in write_stl_file

meshmode/discretization/connection/chained.py, meshmode/discretization/connection/face.py, meshmode/discretization/visualization.py, meshmode/interop/firedrake/mesh.py, meshmode/interop/nodal_dg.py, meshmode/mesh/__init__.py, meshmode/mesh/generation.py, meshmode/mesh/io.py, meshmode/mesh/processing.py, meshmode/mesh/refinement/__init__.py, meshmode/mesh/refinement/no_adjacency.py, test/test_mesh.py, test/test_meshmode.py
Gave this a try and it seems to not break the world. Yey!
Mostly works towards #283.
=> Change MeshElementGroups from Record to dataclass

meshmode/mesh/generation.py, test/test_mesh.py, test/testmesh.msh
Curiously, there *are* some disagreements here.
cc @lukeolson
=> `test_element_orientation_via_single_elements` (from @lukeolson)

meshmode/dof_array.py, test/test_array.py
=> DOFArray: Pickle/unpickle tags

meshmode/discretization/connection/direct.py
=> Avoid bad indexing into 0-long axes

meshmode/mesh/generation.py, test/test_mesh.py, test/test_meshmode.py
Needed for inducer/grudge#256.
=> Allow box meshes to be empty

meshmode/discretization/connection/direct.py, test/test_connection.py
cc @MTCam 
Closes https://github.com/inducer/grudge/issues/258.
=> Add `DirectDiscretizationConnection.is_permutation`

meshmode/dof_array.py
See https://github.com/inducer/arraycontext/pull/158#issuecomment-1120080728 for context.
- :warning: Needs to go in conjunction with https://github.com/inducer/arraycontext/pull/158
=> Support `with_array_context` for DOFArrays

meshmode/transform_metadata.py
FYI @kaushikcfd 
Was missing a `Dim` for consistency.
=> Fix name of DiscretizationTopologicalDimAxisTag

doc/conf.py, meshmode/discretization/connection/direct.py
The doc config commit resolves CI failures like https://github.com/inducer/meshmode/actions/runs/2522691545.
=> Add more `NameHint`s

meshmode/mesh/generation.py
Change docstrings in generation.py
=> Comment in test_curves [0,1) to [0,1]

examples/from_firedrake.py
Fixes https://github.com/inducer/meshmode/actions/runs/3075866331/jobs/4969620685#step:5:23.
=> Fix new matplotlib error in Firedrake examples CI

meshmode/__init__.py, meshmode/mesh/__init__.py, test/test_mesh.py
=> Use elementwise size in node vertex consistency check

meshmode/mesh/generation.py, meshmode/mesh/processing.py, test/test_mesh.py
Mostly to recreate some configurations from Greengard / Martinsson papers.
=> Add helper that creates a grid of curves / surfaces

meshmode/mesh/generation.py, meshmode/mesh/refinement/__init__.py, meshmode/mesh/refinement/no_adjacency.py, meshmode/mesh/refinement/utils.py
And a bold
```
```
at the top!
=> Add types to all of mesh.generation

examples/moving-geometry.py, examples/parallel-vtkhdf.py, meshmode/mesh/processing.py, run-mypy.sh, setup.cfg
Following #357.
There are some extra changes in here for some functions that weren't handling the `group.vertex_indices == None` case, which `mypy` started complaining about once the functions were typed.
=> Finish up typing meshmode.mesh.processing

meshmode/interop/firedrake/mesh.py
To address this type of CI failure:
```
Traceback (most recent call last):
File "/home/firedrake/meshmode/examples/to_firedrake.py", line 130, in <module>
main()
File "/home/firedrake/meshmode/examples/to_firedrake.py", line 86, in main
fd_connection = build_connection_to_firedrake(discr, group_nr=0)
File "/home/firedrake/firedrake/lib/python3.10/site-packages/meshmode/interop/firedrake/connection.py", line 785, in build_connection_to_firedrake
export_mesh_to_firedrake(discr.mesh, group_nr, comm)
File "/home/firedrake/firedrake/lib/python3.10/site-packages/meshmode/interop/firedrake/mesh.py", line 839, in export_mesh_to_firedrake
plex = fd_mesh._from_cell_list(group.dim, cells, coords, comm)
File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
File …
```
=> Adapt to stricter PyOP2 communicator handling

meshmode/interop/firedrake/mesh.py
Incoming comm is now no longer expected to be a PyOP2 communicator.
Follow-up to #363 with less broken interface.
=> Fix PyOP2 communicator-taking logic

.github/workflows/ci.yml, meshmode/discretization/connection/modal.py, meshmode/transform_metadata.py
=> Add tags for all Vandermonde matrix axes

doc/interop.rst, meshmode/discretization/connection/direct.py, meshmode/discretization/connection/face.py, meshmode/discretization/visualization.py, meshmode/interop/firedrake/mesh.py, meshmode/mesh/generation.py, meshmode/mesh/io.py, meshmode/mesh/processing.py, meshmode/mesh/refinement/utils.py, meshmode/mesh/tools.py, test/test_meshmode.py, test/test_modal.py, test/test_partition.py
Was looking through `mesh.generation` and found some typos, so went ahead and linted the whole thing. The commits should be fairly self-contained.
=> Small doc and linting fixes

.test-conda-env-py3.yml
Conda started finding solutions with pocl 1.3 for reasons I wasn't able to discover.
=> Debug crashes 2023-09

.github/workflows/ci.yml, .gitlab-ci.yml, meshmode/mesh/generation.py, test/test_mesh.py
=> Fix, test `generate_urchin`

meshmode/mesh/generation.py
=> mesh.generation: port away from simplex_onb

meshmode/mesh/processing.py
Latest version complains about it.
=> ruff: fix C419 unnecessary list comprehension

meshmode/discretization/visualization.py
=> Remove useless else (RUF047)

meshmode/array_context.py
Needed for inducer/pytato#614.
=> Avoid duplication in `untag_loopy_call_results`

.basedpyright/baseline.json, examples/parallel-vtkhdf.py, meshmode/mesh/__init__.py, meshmode/mesh/generation.py, meshmode/mesh/processing.py, meshmode/mesh/refinement/utils.py
Mostly `np.ndarray` to `NDArray[np.floating]`, but it also has some other small typing updates.
=> Improve types in mesh.generation

meshmode/mesh/io.py
Adds `output_file_name` back to `generate_gmsh` (and deprecates it). Adds `output_file_path` that can point outside of the current working directory.
Draft because:
=> Restore/deprecate `output_file_name` and add `output_file_path`
