- meshmode/distributed.py
- meshmode/mesh/__init__.py
- test/test_partition.py
> Allow get_partition_by_pymetis to partition by facial (rather than nodal) adjacency

- meshmode/mesh/__init__.py
- meshmode/mesh/io.py
Documentation specifies `boundary_tags` as a tuple, but it's used in most places as a list ([example](https://github.com/inducer/meshmode/blob/6cc0de2fec2e39e25dea38035171a74d6021916a/meshmode/mesh/__init__.py#L726-L737)). This makes it officially a list.
cc @MTCam
> Treat boundary_tags as a list consistently

- meshmode/array_context.py
- test/test_meshmode.py
Added to handle an `DOFArray` in [pytential](https://github.com/inducer/pytential/blob/master/pytential/symbolic/execution.py#L287).
As far as I can tell, this should just work™, but the numpy ufunc stuff looks for `conjugate` and the `cl.array.Array` only has a `conj` (i.e. this works fine for object arrays of `ndarray`). This kind of sounds like a bug, since at the toplevel `np.conj` is an alias of `np.conjugate`.
> Add conj to the ArrayContext numpy workalike

- meshmode/discretization/connection/chained.py
- meshmode/discretization/connection/direct.py
- test/test_chained.py
- test/test_meshmode.py
Fixes https://gitlab.tiker.net/inducer/meshmode/-/issues/13
> Deprecate DirectDiscretizationConnection.full_resample_matrix

- meshmode/array_context.py
Another silly one-liner that fixes the rendering [here](https://documen.tician.de/meshmode/array.html#meshmode.array_context.PyOpenCLArrayContext.allocator).
> Add missing space in array context docs

- meshmode/discretization/__init__.py
- test/test_meshmode.py
Managed to hit this in [pytential](https://github.com/inducer/pytential/blob/master/pytential/symbolic/execution.py#L219) when using multiple groups. That passed in a generator that got consumed by the first group.
> Fix num_reference_derivative for multiple groups

- meshmode/discretization/visualization.py
I would like to tweak `write_vtk_file` slightly so that it can handle the situation where the name_and_fields list contains an empty/None field array.
Example:
```python
names_and_fields = [("cv", ConservedVars), ("foo", Bar)]
```
This PR fixes the write-time error experienced by _mirgecom_ when writing singe-component fluid solutions.
> Update write_vtk so it can handle empty data fields

- meshmode/__init__.py
- meshmode/mesh/generation.py
- meshmode/mesh/visualization.py
- test/test_meshmode.py
The resulting `nodes` were 2d even for a 2d surface embedded in 3d space.
> Fix make_group_from_vertices for tensor product elements

- doc/conf.py
- examples/simple-dg.py
- meshmode/array_context.py
- meshmode/discretization/__init__.py
- meshmode/discretization/visualization.py
- meshmode/dof_array.py
- meshmode/interop/nodal_dg.py
- test/test_array.py
- test/test_firedrake_interop.py
- test/test_meshmode.py
Having `DOFArray` be a subclass of `numpy.ndarray` had the potential to be confusing. For example, @MTCam ran into a situation where `DOFArray + np.ndarry([0.1, 0.2])` produced a `DOFArray` that (technically) represented DOFs for a discretization with two groups, because of unintended broadcasting. This change catches that problem (and, likely, other confusing behaviors) at the source and raises an error right away.
To merge:
- https://github.com/inducer/grudge/pull/29
- https://github.com/illinois-ceesd/mirgecom/pull/149
- https://github.com/inducer/pytential/pull/36
cc @MTCam @kaushikcfd @alexfikl @majosm @w-hagen @lukeolson
> Stop subclassing DOFArray from numpy.ndarray

- meshmode/array_context.py
- test/test_array.py
> Fix, test array context reductions

- meshmode/array_context.py
It's a [documented](https://numpy.org/doc/stable/reference/generated/numpy.absolute.html) shorthand for `absolute`.
> Add abs shorthand to array context

- meshmode/dof_array.py
Adds broadcasting operations between `DOFArray` and numpy arrays. Removes the need to use `make_obj_array([...])` for scalars, e.g.:
```diff
- np.outer(mom, mom)/make_obj_array([cv.mass]) + np.eye(dim)*make_obj_array([p])
+ np.outer(mom, mom)/cv.mass + np.eye(dim)*p
```
> Broadcast DOFArray across numpy arrays in binary operations

- .github/workflows/ci.yml
- .gitignore
- .test-conda-env-py3.yml
- doc/conf.py
- meshmode/discretization/visualization.py
- requirements.txt
- setup.py
- test/test_meshmode.py
Uses inducer/pyvisfile#12 to write out some XDMF + HDF5 files (requires h5py of course). It reuses the linear VTK connectivity but I had to write one XDMF Grid per group because I couldn't convince Paraview to index into arrays properly.
One nice benefit of these things is that HDF5 seems to be quite a bit better at compression. From running `test_meshmode.py::test_visualizers`:
```
>> ls -lSh
2.0M Dec 30 20:27 visualizer_vtk_simplex_3d_linear.vtu
846K Dec 30 20:27 visualizer_vtk_simplex_3d_lagrange.vtu
286K Dec 30 20:27 visualizer_xdmf_simplex_3d.h5
1.3K Dec 30 20:27 visualizer_xdmf_simplex_3d.xmf
```
> Xdmf Visualizer

- meshmode/dof_array.py
- test/test_array.py
Added `iadd`, `isub`, `imul` and `itruediv`. There's some more in `cl.Array` that could be added, but I mostly just needed these.
> Add some in-place operators to DOFArray

- .github/workflows/ci.yml
- .test-conda-env-py3.yml
- meshmode/mesh/__init__.py
Rewrites `_compute_facial_adjacency_from_vertices` using numpy in order to try to fix illinois-ceesd/mirgecom#202.
> Compute facial adjacency with numpy

- meshmode/mesh/visualization.py
- test/test_refinement.py
This adds a failing test for the ability to refine toruses and spheres without large node-vertex inconsistencies.
I'm guessing this might have to do with the work in #97. I don't yet fully understand what's going on.
cc @alexfikl
> (WIP) Fix surface refinement

- meshmode/discretization/__init__.py
- meshmode/discretization/connection/face.py
- meshmode/discretization/connection/refinement.py
- meshmode/discretization/visualization.py
- meshmode/distributed.py
- meshmode/mesh/__init__.py
Address the first (and simplest) point from #123.
I went with copy instead of replace because similar classes are based on `pytools.Record` and it uses copy.
> Add a copy method to Discretization

- test/test_meshmode.py
Does exactly what it suggests :smile: 
This is based on some testing using the conda environment created via https://github.com/illinois-ceesd/emirge, and a conversation with @inducer.
It appears that using OpenBLAS from conda forge produces slightly different computed values in `test_meshmode.py`, causing test failures when using the conda environment for Mirgecom.
> Slightly adjust test tolerance

- meshmode/mesh/__init__.py
- meshmode/mesh/generation.py
- test/test_meshmode.py
Included changes:
* Adds a test that uses interior quadrature nodes in the `Mesh`.
* Adds a `unit_nodes` argument to `generate_icosphere` and `generator_torus`.
It seems to be working as expected. The only hiccup is that it requires a lot more elements to actually pass `_test_node_vertex_consistency`.
> Test for mesh with interior nodes

- meshmode/discretization/__init__.py
This feels a bit dumb, but it works for my use case. Thoughts?
Work towards last point in #123
> Skip node resampling in discretization

- meshmode/discretization/visualization.py
- test/test_meshmode.py
This tries to avoid rebuilding all the connectivity when doing IO for moving meshes (see #123).
I started doing a proper copy, but it seemed like too many things could get inconsistent. The current version just replaces the underlying discretization.
> Add simple copy to Visualizer

- meshmode/array_context.py
- meshmode/version.py
This is intended to make metadata capture available generically, even if it boils down to a no-op for the PyOpenCL array context. @kaushikcfd, could you review? I'm particularly curious what you think of `tag_axis` and the `CommonSubexpression` tag.
cc @MTCam @nchristensen @alexfikl
> Add tagging functionality to the array context

- meshmode/array_context.py
- meshmode/dof_array.py
Forcing all array contexts to support `arr1 == arr2` for elementwise comparison is quite restrictive. This PR gets rid of that restriction.
> Generalize array comparison logic

- examples/moving-geometry.py
- examples/simple-dg.py
- meshmode/discretization/__init__.py
- meshmode/discretization/connection/projection.py
- meshmode/discretization/poly_element.py
- test/test_meshmode.py
This does a couple of things
* Makes `num_reference_derivative` a function (part of #141)
* Makes `mass_matrix`, `diff_matrices` and `from_mesh_interp_matrix` functions (part of #141)
* ~~Adds the results to a global cache (helps with #123)~~
Fixes #141
> Move ElementGroup matrix methods to functions

- doc/conf.py
- doc/distributed.rst
- doc/index.rst
- meshmode/distributed.py
- test/test_partition.py
I found the source of my CI hangs in #133. `MPIBoundaryCommSetupHelper` was doing something not so safe: it was waiting on its send request immediately after receiving, instead of waiting until all the receives are done. This PR tweaks its API to allow waiting on the sends separately.
I think grudge managed to avoid bumping into this because it completes the receives in order (unlike the partition tests here).
:warning:  Should land at the same time as https://github.com/inducer/grudge/pull/63
> Fix bug in MPIBoundaryCommSetupHelper

- meshmode/discretization/poly_element.py
Thanks to @alexfikl for fixing this in modepy! This just carries over that change into meshmode.
> Use `ZeroDimensionalQuadrature` for 0-dim reference cells

- meshmode/discretization/__init__.py
- meshmode/discretization/connection/modal.py
- meshmode/discretization/poly_element.py
- test/test_modal.py
Retires `weights` and instead exposes a `modepy.Quadrature` object associated with relevant element groups
> Make `quadrature_rule` a public-facing method

- meshmode/mesh/generation.py
* Added some typing to curves and surfaces.
* Updated docs a bit to match.
* Added ability to disable node consistency checks.
* Updated some usage of `np.random` and `refine_uniformly` for the icosphere.
I also added some `*` (as in `func(arg0, *, kwarg)`) to some functions that may break backwards compatibility here.
> Some cleanups for surfaces in meshmode.mesh.generation

- meshmode/array_context.py
- test/test_array.py
Added so that they can distribute nicely over `DOFArrays`.
Should supersede what was in #139 (at some point).
> Add empty_like and friends to ArrayContext.np

- meshmode/interop/firedrake/connection.py
Possible context: https://github.com/firedrakeproject/firedrake/commit/641fdf3d9ce54c26e2b20c1478488d0313b4c351
Hoping to address these failures seen in #181, #175.
```
Traceback (most recent call last):
File "/__w/meshmode/meshmode/test/test_firedrake_interop.py", line 620, in test_from_fd_idempotency
restrict_to_boundary="on_boundary")
File "/home/firedrake/firedrake/lib/python3.6/site-packages/meshmode/interop/firedrake/connection.py", line 725, in build_connection_from_firedrake
restrict_to_boundary)
File "/home/firedrake/firedrake/lib/python3.6/site-packages/meshmode/interop/firedrake/connection.py", line 598, in _get_cells_to_use
boundary_nodes = cfspace.boundary_nodes(bdy_id, "topological")
TypeError: boundary_nodes() takes 2 positional arguments but 3 were given
```
@wence- Is …
> Track Firedrake changes to FunctionSpace.boundary_nodes

- examples/simple-dg.py
- meshmode/array_context.py
- meshmode/discretization/connection/chained.py
- meshmode/discretization/connection/direct.py
- meshmode/discretization/connection/modal.py
- meshmode/discretization/connection/projection.py
- meshmode/discretization/visualization.py
- meshmode/dof_array.py
- test/test_array.py
- test/test_chained.py
- test/test_interop.py
- test/test_meshmode.py
- test/test_modal.py
- test/test_partition.py
- test/test_refinement.py
This was previously in #139, but opened a new clean PR without all the unrelated comments.
Current functionality:
* Added a barebones `ArrayContainer` class that just defines a serialization protocol for its components.
* Added a subclass `ArrayContainerWithArithmetic` that should allow to easily add new custom classes. `DOFArray` now steals all its arithmetic from here.
* Implemented a `map_array_container` and `multimap_array_container` that recurses through a tree of containers and applies a function to all their components.
* Implemented a `freeze` and `thaw` based on those that seem to work nicely enough.
* On the `DOFArray` side, added some `map_dof_array_container` and friends that stop recursing when they hit `DOFArrays`.
There's an example in `test_array` that shows how to extend …
> Add a generic ArrayContainer

- .ci/install-for-firedrake.sh
- meshmode/interop/nodal_dg.py
This was failing very frequently on gitlab, and I had to go check every time to see if it was an actual failure or just *that again*. It finally annoyed me sufficiently.
> Firedrake CI, fix delay-setting code for oct2py in nodal-dg interop

- meshmode/dof_array.py
- test/test_chained.py
- test/test_meshmode.py
This basically just moves the code from pytential
https://github.com/inducer/pytential/blob/main/pytential/utils.py
with `flatten_if_needed` getting folded into `flatten` by just doing nothing if it's passed a non-`DOFArray`.
I have a version of these functions in my code as well and they're pretty useful for talking with the outside world. Doing `map_dof_array_container(actx.to_numpy, flatten(ary))` isn't too long either, but that's two traversals.
There's a version of pytential using this stuff at inducer/pytential#88.
> Add flatten and unflatten to numpy

- examples/from_firedrake.py
- examples/moving-geometry.py
- examples/plot-connectivity.py
- examples/to_firedrake.py
- meshmode/__init__.py
- meshmode/discretization/connection/chained.py
- meshmode/discretization/connection/direct.py
- meshmode/interop/firedrake/connection.py
- meshmode/interop/nodal_dg.py
- test/test_array.py
- test/test_discretization.py
- test/test_firedrake_interop.py
- test/test_interop.py
- test/test_mesh.py
- test/test_modal.py
- test/test_partition.py
- test/test_refinement.py
- test/test_visualization.py
This should get rid of all the deprecated calls.
> Port away from meshmode.array_context

- examples/simple-dg.py
- meshmode/discretization/__init__.py
- meshmode/discretization/connection/direct.py
- meshmode/discretization/connection/modal.py
- meshmode/discretization/connection/projection.py
- meshmode/dof_array.py
- test/test_chained.py
Supercedes: https://github.com/inducer/meshmode/pull/180 and https://github.com/inducer/meshmode/pull/58
Requires: https://github.com/inducer/arraycontext/pull/8 and https://github.com/inducer/arraycontext/pull/9
> Remove stateful updates

- meshmode/mesh/__init__.py
- meshmode/mesh/processing.py
Pulled out of #204 to declutter.
> Misc. distributed fixes/tweaks

- meshmode/mesh/__init__.py
Pulled out of #204 to declutter.
:warning: Remove `_FlatFacialAdjacencyData` again before merging. :warning:
> Separate face matching from _compute_facial_adjacency_from_vertices

- meshmode/dof_array.py
> Make flat_norm compatible with all array contexts

- examples/moving-geometry.py
- examples/plot-connectivity.py
- examples/simple-dg.py
- experiments/refinement-playground.py
- meshmode/discretization/connection/direct.py
- meshmode/discretization/connection/opposite_face.py
- meshmode/discretization/poly_element.py
- meshmode/dof_array.py
- meshmode/interop/firedrake/connection.py
- meshmode/mesh/generation.py
- meshmode/mesh/visualization.py
- setup.py
- test/test_array.py
- test/test_connection.py
- test/test_mesh.py
- test/test_meshmode.py
- test/test_modal.py
- test/test_partition.py
- test/test_refinement.py
- test/test_visualization.py
This is supposed to be a version of #105 that we can merge right away, plus a number of fixes that arose around that. For review, this PR is probably best viewed commit-by-commit. The commit messages provide a pretty good inventory of what's here.
Diff-wise, the biggest part of this is the (annoying, but IMO required) split of `PolynomialWarpAndBlendGroupFactory` into `PolynomialWarpAndBlend2DGroupFactory` and `PolynomialWarpAndBlend3DGroupFactory`. (The 2D WnB nodes are *not* equivalent to a restriction of the 3D nodes to a face, and we very much would like 2D el groups in 3D discretizations to be just that, so that the boundary extractions can be done by indirect addressing.)
cc @nchristensen
> Test that connections that should be permutations actually *are* permutations

- meshmode/discretization/connection/opposite_face.py
- test/test_connection.py
While it doesn't actually solve the problem described in https://github.com/inducer/meshmode/pull/105#issuecomment-862003829, this should work around the main impact of #105: The DG examples no longer use matvecs to interpolate onto the boundary. This should help speed up larger-scale DG runs somewhat.
Draft because:
Post-merge:
@majosm Could you review this? I know it'll likely have a little bit of conflict with #204, but `_make_cross_face_batches` was getting crazy long. Hopefully the conflicts won't be bad: the diff doesn't touch any of the actual functionality, it just shuffles function arguments around.
cc @nchristensen @matthiasdiener
> _make_cross_face_batches: refactor into multiple functions, try matching nodes exactly before going to Gauss-Newton

- .ci/install-for-firedrake.sh
- meshmode/discretization/connection/direct.py
- requirements.txt
- test/test_meshmode.py
This reverts #217 and thereby makes meshmode lazy-compatible again. 
In an earlier version of this, I said:
> There should not be a performance hit this time.
Turns out that that statement was a bit optimistic. See below.
cc @thomasgibson @matthiasdiener
> Undo revert of connection kernels to pre-#192

- meshmode/discretization/connection/direct.py
x-ref: https://github.com/inducer/loopy/issues/427
cc @thomasgibson 
Fixes these crashes observed in GPU CI: https://gitlab.tiker.net/inducer/meshmode/-/jobs/283720
> Work around loopy behavior with reductions in ternary

- meshmode/discretization/visualization.py
This adds relative file path support for visualization file names.
Without this change, specifying relative filenames for the visualization file works OK, except for the filenames listed in the parallel manifest, which had previous retained the relative filenames.  This change massages the filenames listed in the parallel manifest so as to drop the relative pathing.
> Add relative path support for visualization file names.

- .ci/install-for-firedrake.sh
- doc/array.rst
- examples/from_firedrake.py
- examples/moving-geometry.py
- examples/plot-connectivity.py
- examples/simple-dg.py
- examples/to_firedrake.py
- meshmode/__init__.py
- meshmode/array_context.py
- meshmode/discretization/__init__.py
- meshmode/discretization/connection/direct.py
- meshmode/discretization/connection/modal.py
- meshmode/discretization/connection/projection.py
- meshmode/dof_array.py
- meshmode/transform_metadata.py
- test/test_array.py
- test/test_chained.py
- test/test_connection.py
- test/test_discretization.py
- test/test_firedrake_interop.py
- test/test_interop.py
- test/test_mesh.py
- test/test_meshmode.py
- test/test_modal.py
- test/test_partition.py
- test/test_refinement.py
- test/test_visualization.py
This supersedes https://github.com/inducer/arraycontext/pull/29, in that it never made sense that `arraycontext` had to know anything about how to transform FEM-related programs. Together with https://github.com/inducer/arraycontext/pull/50, this PR fixes that.
This PR is probably best read commit-by-commit.
If you'd like to run this, you'll need https://github.com/inducer/loopy/pull/445 (already merged at the time of this writing).
Draft (but ready for review) because:
> Teach meshmode about FEM program transformation

- meshmode/dof_array.py
This is a fairly "hot' code path, and this shaves off a few percent of cost.
> Skip input validation in DOFArray constructor unless __debug__

- meshmode/dof_array.py
`DOFArray`s are automagically truthy because they implement `__len__`. Hopefully this wasn't used in too many places.
Requires inducer/arraycontext#66 (for the error message to be useful)
> Disable __bool__ on DOFArray

- .test-conda-env-py3.yml
- test/test_partition.py
I'm guessing `mpi4py` started pulling in `mpich` instead of `openmpi` in the CI (although couldn't find any changes in the conda-forge packages?) and `test_partition` started failing because it couldn't find the `--oversubscribe` flag.
This just adds `openmpi` to the conda env.
> Only oversubscribe on openmpi

- meshmode/discretization/connection/direct.py
- meshmode/discretization/connection/projection.py
- meshmode/discretization/visualization.py
- meshmode/dof_array.py
- meshmode/interop/firedrake/connection.py
I observed that it's currently possible to feed a `DOFArray` for a non-matching discretization to a visualizer or a connection. This adds some checks to catch that. That isn't free, but IMO it's well worth the cost. I'm honestly almost expecting to see some failures in CI, which would immediately prove the worth of these changes.
> Check `DOFArray` group array sizes in connections and visualization

- doc/mesh.rst
- meshmode/__init__.py
- meshmode/discretization/connection/face.py
- meshmode/discretization/connection/opposite_face.py
- meshmode/distributed.py
- meshmode/interop/firedrake/mesh.py
- meshmode/mesh/__init__.py
- meshmode/mesh/generation.py
- meshmode/mesh/io.py
- meshmode/mesh/processing.py
- meshmode/mesh/tools.py
- test/test_firedrake_interop.py
- test/test_mesh.py
- test/test_partition.py
This PR:
1. Restructures `Mesh`'s facial adjacency structure to allow multiple adjacency groups for each pair of mesh element groups. In other words, `List[Dict[FacialAdjacencyGroup]]` becomes `List[List[FacialAdjacencyGroup]]`.
2. Splits `FacialAdjacencyGroup` into `InteriorAdjacencyGroup` and `BoundaryAdjacencyGroup` subclasses (with `InterPartitionAdjacencyGroup` inheriting from `BoundaryAdjacencyGroup`).
3. Splits boundary adjacency for different boundary tags into different groups.
4. Splits inter-partition adjacency for different ranks into different groups.
5. Removes `boundary_tags`/`boundary_tag_bit` from `Mesh`.
6. Adds affine transformations to `InteriorAdjacencyGroup`/`InterPartitionAdjacencyGroup`.
~~This will almost certainly need to be split into multiple PRs~~, but I …
> Overhaul facial adjacency + boundary tagging

- doc/Makefile
- meshmode/discretization/__init__.py
- meshmode/discretization/poly_element.py
- meshmode/discretization/visualization.py
- meshmode/mesh/visualization.py
Explicitly using `OrderAndTypeBasedGroupFactory` everywhere (in inducer/pytential#46) was getting a bit verbose.
This basically introduces a `HeterogeneousOrderBasedGroupFactory` (naming?) that's supposedly a bit more extensible than `OrderAndTypeBasedGroupFactory` and a bunch of subclasses for the common cases that meshmode/grudge/pytential use.
Not quite sure how future proof this is, so suggestions welcome!
> Introduce MeshElementGroup-generic group factories

- meshmode/discretization/visualization.py
- test/test_visualization.py
Not quite sure what it was doing before (just taking the real part somewhere?), but in matplotlib 3.5 they added an extra check that raises on complex inputs.
> Disallow complex fields in matplotlib visualizer

- meshmode/array_context.py
- meshmode/discretization/connection/direct.py
- test/test_meshmode.py
Why is this approach better?
For PytatoArrayContext: cleaner to fuse over other possible approach of inferring the semantics of a loopy call.
Draft because:
---
> resample_by_picking: use array expressions

- meshmode/mesh/generation.py
It now doesn't assume `QN` and should work with the new tensor product spaces from inducer/modepy#41.
> Use space_for_shape in make_group_from_vertices

- meshmode/discretization/__init__.py
Was timing the pytential FMM on moving geometries and noticed that a lot of its caches (like [this one](https://github.com/inducer/pytential/blob/87ba4e4be2ab63503f3c4e554e8c9667a1f25f67/pytential/qbx/__init__.py#L340-L346)) kept going away because the `_setup_actx` kept getting cloned.
This updates `Discretization.copy` to only make a clone if it's given a new `actx`, but keep the existing `_setup_actx` as is otherwise.
EDIT: this seems to save about 10%-15% of the time in my small `pytential` benchmark.
> Disable actx.clone on discr.copy

- .gitignore
- .test-conda-env-py3.yml
- examples/parallel-vtkhdf.py
- meshmode/discretization/visualization.py
- test/test_visualization.py
Found out that VTK has support for HDF5 too (not sure since when?)
https://vtk.org/doc/nightly/html/VTKHDFFileFormat.html
and implemented a little writer for it. It should be better than the XDMF writer in the long run, since that seems generally unmaintained.
It has similar benefits with smaller file sizes. From the test in `test_visualization`
```
2.0M visualizer_vtk_simplex_3d_linear.vtu
1.5M visualizer_vtkhdf_simplex_3d_linear.hdf
```
Big plus is that it supports MPI too so there's no need for that `pvtu` stuff with a gazillion files!
EDIT: Tested with Paraview 5.10 and no guarantees for other version.
> Add support for VTKHDF

- meshmode/discretization/visualization.py
Just realized I didn't really check the 2D case.. and indeed it wasn't working. 
Paraview just crashed in some `vtkPoints` class saying it didn't have enough dimensions. This seems to fix it, but it's not great to store a bunch of zeros. Not sure if there's some better way..
> Pad arrays to 3d in write_vtkhdf_file

- meshmode/mesh/__init__.py
cc @anderson2981 @MTCam @majosm @lukeolson
> Do not use `assert` for mesh orientation check

- meshmode/discretization/connection/opposite_face.py
- meshmode/discretization/visualization.py
- meshmode/distributed.py
- meshmode/mesh/__init__.py
- meshmode/mesh/generation.py
- meshmode/mesh/processing.py
- meshmode/mesh/refinement/no_adjacency.py
- meshmode/mesh/refinement/utils.py
- meshmode/mesh/visualization.py
- test/test_partition.py
* Adds a `Mesh.element_nr_base` and `Mesh.node_nr_base`, which are arrays of size `len(groups)`.
* Uses those everywhere instead of `MeshElementGroup.element_nr_base` and `node_nr_base`, except in `refinement.Refiner` since that's supposed to go away anyway.
`element_nr_base` and `node_nr_base` are still set in `Mesh.__init__` in case anyone uses them, so not quite sure how to deprecate them.
Work towards #224.
> Remove uses of MeshElementGroup.element_nr_base

- meshmode/mesh/__init__.py
- meshmode/mesh/io.py
* `join_mesh` accessed `element_nr_base` and complained on every mesh construction.
* `__eq__` also compared `element_nr_base`, which shouldn't be valid anymore.
Also fixed the deprecation warning, which wasn't pointing to the correct attribute on `Mesh`.
> Less noisy element_nr_base deprecation

- meshmode/discretization/__init__.py
- meshmode/discretization/connection/modal.py
- meshmode/discretization/connection/projection.py
- meshmode/discretization/connection/refinement.py
- meshmode/discretization/poly_element.py
- meshmode/interop/firedrake/connection.py
- setup.py
This deprecates the `index` attribute
* Set `index=None` in `ElementGroupBase` and issue a deprecation warning.
* Set `index=None` in `ElementGroupFactory.__call__` too.
The last two commits are independent and just do some random cleanup in `meshmode.discretization.__init__`. I can pluck those out into a separate PR if that's easier.
Second part of #224.
> Deprecate ElementGroupBase.index

- meshmode/mesh/__init__.py
- meshmode/mesh/visualization.py
- test/test_visualization.py
Used while looking at #310 yesterday and thought it may be useful. What do you think?
Added some types in a second commit, so probably best viewed individually.
> Add a way to visualize the mesh node-vertex resampling error

- meshmode/discretization/connection/direct.py
- test/test_meshmode.py
Supersedes #259. The automatic merge was sufficiently bad that I decided to start from scratch, copy-pasting code over.
Still to do:
This seems to have a pretty marked benefit. Using `wave-op-mpi.py` from grudge, before:
```
INFO:pytato.partition:find_partition: Split 326 nodes into 1 parts, with [270] nodes in each partition. 
```
and after:
```
INFO:pytato.partition:find_partition: Split 210 nodes into 1 parts, with [176] nodes in each partition.   
```
cc @kaushikcfd
> Merge pickable interpolation batches in direct connection

- meshmode/mesh/io.py
- test/test_mesh.py
- test/testmesh.msh
- test/testmesh_multivol.msh
> Optionally return volume-tag-to-element map from `read_gmsh` 

- .test-conda-env-py3.yml
- Works around https://github.com/conda-forge/openmpi-feedstock/issues/94
- Uses same workaround as https://github.com/conda-forge/lfpy-feedstock/pull/31/files
> Work around accidental installation of 'external' flavor of c-f ompi

- .test-conda-env-py3.yml
This reverts commit 5c5889aa48ca79d82c81e7e57f613a527c446a77.
Should no longer be needed because of https://github.com/conda-forge/openmpi-feedstock/pull/98.
> Revert "Work around accidental installation of 'external' flavor of cf-ompi"

- meshmode/array_context.py
- meshmode/discretization/__init__.py
- meshmode/discretization/connection/direct.py
- meshmode/discretization/connection/face.py
- meshmode/discretization/connection/modal.py
- meshmode/discretization/connection/same_mesh.py
- meshmode/discretization/visualization.py
- meshmode/transform_metadata.py
> Add transform metadata to describe arrays' axes types

- doc/conf.py
- meshmode/discretization/connection/direct.py
- meshmode/discretization/connection/opposite_face.py
- meshmode/distributed.py
- meshmode/mesh/__init__.py
- meshmode/mesh/generation.py
- meshmode/mesh/processing.py
- test/test_partition.py
- test/test_refinement.py
To do before merging:
cc @majosm
> Allow distributed partition boundaries to be not just rank boundaries

- test/test_modal.py
Sample test failure: https://gitlab.tiker.net/inducer/pyopencl/-/jobs/447952
> Bump tolerance in test_quadrature_based_modal_connection_reverse

- meshmode/mesh/generation.py
Reorders box generator's facial/boundary adjacency loop s.t. it checks every boundary for every element instead of checks every element for every boundary.  This limits the number of times we need to visit every element to check adjacency.  
fixes #350
> Reorder box generator facial/boundary adjacency loops

- meshmode/mesh/generation.py
- test/test_mesh.py
This adds a piecewise construction, since that seemed easier. It looks like this:
<p align=center>
</p>
There's some knobs to control the radius of the outer circle, the inner circle and the size of the gap in front. It should only be C0 though. Do you think it's worth adding a Fourier interpolated smooth version?
> Add a simple piecewise C geometry

- meshmode/interop/firedrake/mesh.py
- test/test_firedrake_interop.py
https://github.com/firedrakeproject/firedrake/commit/9125a65c0cb5bb671c62c33f05a0d42b983e06ed, in which 'deprecate' appears to mean 'remove without prior warning or suggested recourse'.
CI failure: https://github.com/inducer/meshmode/actions/runs/4395544902
> Fix for Firedrake removing `_Facets.markers`

- examples/parallel-vtkhdf.py
- meshmode/distributed.py
- test/test_partition.py
cf. https://github.com/inducer/meshmode/pull/342.
> Deprecate `MPIMeshDistributor`

- meshmode/discretization/connection/direct.py
(e.g. np.ndarray)
cc https://github.com/inducer/arraycontext/pull/235
> _reshape_and_preserve_tags: support untaggable arrays

- meshmode/discretization/visualization.py
Otherwise this would fail in a confusing manner somewhere deeper in `modepy` when we actually try to use it.
> Raise an error if no vis_order is provided

- meshmode/dof_array.py
This ~~should fix~~ fixes restart with Numpy actx. cc @MTCam
> DOFArray: support untaggable arrays in setstate

- .ci/install-for-firedrake.sh
- .github/workflows/ci.yml
- meshmode/discretization/connection/direct.py
- meshmode/discretization/poly_element.py
- meshmode/mesh/__init__.py
Without access to the 1D nodes and 1D basis functions used in the tensor product, we are not able to exploit the tensor product structure to reduce the cost required for operator evaluation, e.g. applying a differentiation operator to function data.
This PR:
- Adds functionality to `TensorProductElementGroupBase` to store and retrieve 1D basis functions and 1D nodes used in the tensor product
- Updates subclasses accordingly
Depends on:
> Tensor product 1d nodes & basis functions

- .github/workflows/ci.yml
The CI was complaining that there's no `standalone.cls` when building tikz pictures.
https://github.com/inducer/meshmode/actions/runs/8585855922/job/23527696674
This installs `texlive-latex-extra` to fix that. At least that's where `standalone.cls` is on Arch, so fingers crossed :worried:
> ci: fix tikz generation

- doc/conf.py
- meshmode/__init__.py
- meshmode/mesh/__init__.py
- meshmode/mesh/io.py
Small followup to #400: this makes `check_mesh_consistency` raise some helpful exceptions with more details about what the inconsistency is, instead of just using `assert`.
The check in `make_mesh` is still only done `if __debug__` though.
> Improve mesh consistency check

- meshmode/discretization/visualization.py
- meshmode/mesh/__init__.py
- meshmode/mesh/processing.py
- test/test_array.py
- test/test_meshmode.py
There's still a bunch of warnings about SVM memory like
```
<generated code for 'invoke_frozen_nodes1_2d_loopy_kernel'>:131: InconsistentOpenCLQueueWarning: Array has different queue from backing SVM memory. This may lead to the array getting deallocated sooner than expected, potentially leading to crashes.
```
and some more loopy warnings, but everything else should be clean.
> Fix warnings and deprecations

- examples/parallel-vtkhdf.py
- meshmode/discretization/connection/direct.py
- meshmode/distributed.py
- meshmode/mesh/processing.py
- setup.py
- test/test_partition.py
Partially addresses https://github.com/inducer/pytato/issues/498
> Mesh Distribution: determinism fixes

- test/test_partition.py
Should fix CI failures like https://gitlab.tiker.net/inducer/meshmode/-/jobs/714915.
> Switch to meshmode actx in `test_mpi_communication`

- examples/moving-geometry.py
- examples/plot-connectivity.py
- examples/simple-dg.py
- meshmode/discretization/poly_element.py
- meshmode/mesh/processing.py
- test/test_array.py
- test/test_mesh.py
- test/test_meshmode.py
Mostly around `inverse_mass_matrix` preferring a `Basis` now, since it was causing a bunch of warnings in grudge as well :grin:
> Fix some deprecations

- meshmode/discretization/__init__.py
- meshmode/discretization/connection/direct.py
- meshmode/mesh/__init__.py
- test/test_array.py
Plus two unrelated commits that popped out while grepping for `actx.zeros` :grin:
> Port to actx.np.zeros

- meshmode/distributed.py
- pyproject.toml
- test/test_firedrake_interop.py
This adds an ignore for https://docs.astral.sh/ruff/rules/unnecessary-literal-within-tuple-call/, since I don't think we want to use generators in tuple calls.
Setting `preview = true` might have been a bit optimistic. They seem to still make a lot of changes in that area even for established rules :\
> Fix issues with ruff 0.5.7

- requirements.txt
The pytential test wasn't running because it wasn't installing `sympy` (likely some change from the `pyproject` migration). This adds the extra dependencies to make sure it runs again.
> Add pytential deps for testing

- meshmode/array_context.py
In preparation for inducer/arraycontext#278.
> Remove uses of deprecated `force_device_scalars=False`

- meshmode/discretization/connection/face.py
The test only works if `mesh.dim == mesh.ambient_dim`, so it always ends up emitting a warning in the `make_mesh` call here.
> Skip element orientation test for face meshes

- doc/interop.rst
- meshmode/discretization/visualization.py
- pyproject.toml
This was required to locally see the errors from
https://github.com/inducer/pytential/actions/runs/10652244738/job/29525807445?pr=164
when everything is installed with `--editable`.
> Fix editable installs

- meshmode/discretization/poly_element.py
Attempting to access the 1D quadratures of the default quadrature rule supplied in `TensorProductElementGroupBase` is not possible. 
This PR makes it so that a `TensorProductQuadrature` is constructed from 1D `Quadrature`s using the 1D interpolation nodes and 1D basis functions associated with `TensorProductElementGroupBase`.
> Use `TensorProductQuadrature` instead of `Quadrature` in `TensorProductElementGroupBase`

- meshmode/discretization/poly_element.py
Didn't catch this yesterday, but expanding tuples inside `ary[...]` is only allowed for >3.10. I think this should be equivalent.
cc @a-alveyblanc
> Make indexing compatible with py3.10

- .ci/install-for-firedrake.sh
- examples/parallel-vtkhdf.py
- meshmode/discretization/connection/face.py
- meshmode/discretization/poly_element.py
- meshmode/discretization/visualization.py
- meshmode/dof_array.py
- meshmode/mesh/__init__.py
- meshmode/mesh/generation.py
- meshmode/mesh/processing.py
- meshmode/mesh/refinement/tessellate.py
- pyproject.toml
- run-mypy.sh
> Modernize 2024

- meshmode/mesh/generation.py
Was looking through some pytential logs and this was making a lot of warnings.
> Prefer importing newer scipy.sph_harm_y

- README.rst
- examples/from_firedrake.py
- examples/moving-geometry.py
- examples/parallel-vtkhdf.py
- examples/plot-connectivity.py
- examples/simple-dg.py
- examples/to_firedrake.py
- examples/tp-lagrange-stl.py
- meshmode/__init__.py
- test/test_partition.py
There don't seem to be other uses in here.
> Remove force_device_scalars=True from examples

- meshmode/mesh/generation.py
- test/test_mesh.py
This just gently modifies `generate_torus_and_cycle_vertices` to allow creating the cruller geometry from https://doi.org/10.1016/j.jcp.2019.109047. Looks like this:
<p align="center">
</p>
> Add a cruller (twisted torus) geometry

- meshmode/discretization/connection/direct.py
- meshmode/mesh/generation.py
- meshmode/mesh/processing.py
- meshmode/mesh/tools.py
- test/test_mesh.py
Reimplements `generate_box_mesh` using numpy, and rearranges some of the boundary processing code to make it faster.
Before (shock1d):
After:
Fixes #456.
To-do:
> Optimize `generate_box_mesh`

- doc/conf.py
- doc/misc.rst
- meshmode/discretization/__init__.py
- meshmode/discretization/connection/__init__.py
- meshmode/discretization/poly_element.py
- meshmode/discretization/visualization.py
- meshmode/mesh/generation.py
- meshmode/mesh/refinement/__init__.py
This didn't have a deadline, but they were deprecated in 2020 (from `git blame`) and there are no uses of the old behavior in `pytential`, `grudge`, etc.
> Remove deprecated keyword in mesh.generation

- meshmode/interop/firedrake/mesh.py
- test/test_firedrake_interop.py
This is a bit of a stab-in-the-dark try to fix the Firedrake failures. 
From my understanding of https://github.com/firedrakeproject/firedrake/pull/4201, the mesh now initializes fully, so this is not needed anymore :crossed_fingers:
> Remove MeshTopology.init calls
